# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "日常"
  url = "a-todo/"
  weight = 10

[[main]]
  name = "技术博客"
  url = "post/"
  weight = 20

[[main]]
  name = "阅读笔记"
  url = "c-readingnotes/"
  weight = 30

[[main]]
  name = "工作笔记"
  url = "d-worknotes/"
  weight = 40

# [[main]]
#   name = "Publications"
#   url = "#featured"
#   weight = 40

[[main]]
  name = "Talk"
  url = "talk/"
  weight = 50
[[main]]
  name = "文档"
  url = "official-docs/"
  weight = 60
[[main]]
  name = "SU2"
  url = "https://su2.kcwm.xyz"
  weight = 70
[[main]]
  name = "NextCloud"
  url = "http://kcwm.xyz:801"
  weight = 80
# [[main]]
#   name = "幻灯片"
#   url = "slides/"
#   weight = 60
# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
